[common]
platform = espressif32@^6.5
board = esp32s3usbotg
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/adafruit/Adafruit_SHTC3.git
    https://github.com/adafruit/Adafruit_MAX1704X
    https://github.com/adafruit/Adafruit_MPL3115A2_Library.git
    blynkkk/Blynk@^1.3.2
build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; ============================================================
; Participant Device Configurations
; Add more participants as needed by duplicating and modifying
; select the respective env in VS code when building or uploading
; or alternatively use the command line with:
; platformio run -e peter_env --target upload OR build
; ============================================================

[env:1]
extends = common
build_flags = 
	'-DBLYNK_TEMPLATE_ID="Your-Template-ID-Here"'
	'-DBLYNK_TEMPLATE_NAME="Name-Weather-Station"'

[env:2]
extends = common
build_flags = 
	'-DBLYNK_TEMPLATE_ID="Your-Template-ID-Here"'
	'-DBLYNK_TEMPLATE_NAME="Name-Weather-Station"'
